# Generated by Django 4.2.8 on 2023-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
