# Generated by Django 4.2.8 on 2023-12-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_text_post_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
    ]
